services:
  app:
    build:
      context: ./backend
    #      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: appz
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    command: >
      bash -c "
      python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /code
    env_file:
      - .env
  db:
    image: postgres:17
    container_name: appz-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

#  dbBackups:
#    image: postgres:17
#    container_name: appz-db-backup
#    restart: always
##    user: postgres:postgres # Optional: see below
#    volumes:
#      - ./backups:/backups
#    links:
#      - db
#    depends_on:
#      - db
#    environment:
#      - POSTGRES_HOST=db
#      - POSTGRES_DB=${DATABASE_NAME}
#      - POSTGRES_USER=${DATABASE_USERNAME}
#      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
#      #  - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
#      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
#      - SCHEDULE=@daily
#      - BACKUP_ON_START=TRUE
#      - BACKUP_KEEP_DAYS=7
#      - BACKUP_KEEP_WEEKS=4
#      - BACKUP_KEEP_MONTHS=6
#      - HEALTHCHECK_PORT=8080
#    env_file:
#      - .env

#  frontend-proxy:
#    build:
#      context: .
#    container_name: appz_proxy
#    image: nginx:latest
#    ports:
#      - "8000:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./static:/static:ro
#    depends_on:
#      - django-web

volumes:
  postgres_data:

networks:
  inside-network:
    driver: bridge